# Generated by Django 3.2 on 2021-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('rnumber', models.CharField(max_length=50, null=True)),
                ('aadharn', models.CharField(max_length=50, null=True)),
                ('pann', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('high', models.CharField(max_length=1000, null=True)),
                ('senior', models.CharField(max_length=1000, null=True)),
                ('aadhar', models.CharField(max_length=1000, null=True)),
                ('pan', models.CharField(max_length=1000, null=True)),
                ('clg', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
