# Generated by Django 3.2 on 2021-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210924_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
