# Generated by Django 3.2 on 2021-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_new_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
