# Generated by Django 3.2 on 2021-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_new_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='comment',
            field=models.CharField(max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
