# Generated by Django 3.2 on 2021-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210925_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
