# Generated by Django 3.2 on 2021-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210929_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='mname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
