# Generated by Django 3.2 on 2021-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='form_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
