# Generated by Django 3.2 on 2021-09-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_new_form_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='form_submitted',
            new_name='submitted',
        ),
    ]
