# Generated by Django 3.2 on 2021-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
