# Generated by Django 3.2 on 2021-10-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_new_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='approved',
            new_name='approved1',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='declined',
            new_name='approved2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='comment',
        ),
        migrations.AddField(
            model_name='new',
            name='approved3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='comment1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='comment2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='comment3',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='declined1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='declined2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='declined3',
            field=models.BooleanField(default=False),
        ),
    ]
