# Generated by Django 3.2 on 2021-10-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211001_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='comment1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='comment2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='comment3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
