# Generated by Django 3.2 on 2021-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211001_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='submitted',
        ),
        migrations.AddField(
            model_name='new',
            name='status1',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Declined')], default=True),
        ),
    ]
