# Generated by Django 3.2 on 2021-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_new_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='status1',
            field=models.BooleanField(blank=True, choices=[(True, 'Approved'), (False, 'Declined')], default=None),
        ),
    ]
