# Generated by Django 3.2 on 2021-10-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_new_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='high',
            field=models.FileField(blank=True, default=None, null=True, upload_to='books/pdfs/'),
        ),
    ]
