# Generated by Django 3.2 on 2021-10-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_new_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='high',
            field=models.FileField(blank=True, default=None, null=True, upload_to='fname + lname'),
        ),
    ]
