# Generated by Django 3.2 on 2021-10-09 13:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211006_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='aadhar',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='college',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='graduation',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='high',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='masters',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='pan',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='phd',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='new',
            name='senior',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
