# Generated by Django 3.2 on 2021-10-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20211009_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
