# Generated by Django 3.2 on 2021-10-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_new_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='dob',
        ),
    ]
