# Generated by Django 3.2 on 2021-10-09 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_new_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
