# Generated by Django 3.2 on 2021-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_new_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='dob',
            field=models.DateField(default=None, null=True, verbose_name='Date'),
        ),
    ]
