# Generated by Django 3.2.7 on 2021-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_new_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='status1',
            field=models.BooleanField(blank=True, choices=[(True, 'Approve'), (False, 'Decline')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='status2',
            field=models.BooleanField(blank=True, choices=[(True, 'Approve'), (False, 'Decline')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='status3',
            field=models.BooleanField(blank=True, choices=[(True, 'Approve'), (False, 'Decline')], default=None, null=True),
        ),
    ]
