# Generated by Django 3.2 on 2021-10-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20211017_1901'),
        ('accounts', '0035_auto_20211018_1838'),
    ]

    operations = [
    ]
