# Generated by Django 3.2 on 2021-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_merge_0035_auto_20211017_1901_0035_auto_20211018_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='gender1',
            field=models.CharField(blank=True, choices=[(None, 'Choose your gender'), ('male', 'male'), ('female', 'female'), ('custom', 'custom'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=50, verbose_name='gender'),
        ),
    ]
