# Generated by Django 3.2.8 on 2021-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_new_gender1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='gender1',
            field=models.CharField(blank=True, choices=[(None, 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=50, verbose_name='gender'),
        ),
    ]
